/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PeterLeung
 */
public class EditFrameGUI extends javax.swing.JFrame {

    
    
    /**
     * Creates new form EditFrameGUI
     */
    public EditFrameGUI() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public EditFrameGUI(String dream) {
        initComponents();
        setLocationRelativeTo(null);
        want.setText(dream);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        want = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reason_want = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        accomplish = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        settings = new javax.swing.JButton();
        new_entry = new javax.swing.JButton();
        feed = new javax.swing.JButton();
        login = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMinimumSize(new java.awt.Dimension(640, 400));
        setResizable(false);
        setSize(new java.awt.Dimension(655, 435));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 2, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("dreamdazer");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 11, 273, 46);

        jLabel3.setFont(new java.awt.Font("Noteworthy", 2, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 255));
        jLabel3.setText("interactive change");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 50, 110, 22);

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 255));
        jLabel2.setText("I want");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(16, 87, 41, 17);

        want.setToolTipText("Enter your goal");
        getContentPane().add(want);
        want.setBounds(80, 80, 282, 26);

        jLabel4.setFont(new java.awt.Font("Yu Gothic", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 255, 255));
        jLabel4.setText("because");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(37, 116, 57, 18);

        reason_want.setColumns(20);
        reason_want.setRows(5);
        reason_want.setToolTipText("Why do you want to reach this goal?");
        jScrollPane1.setViewportView(reason_want);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(16, 140, 396, 84);

        jLabel5.setForeground(new java.awt.Color(0, 255, 255));
        jLabel5.setText("I will accomplish this by...");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(16, 242, 165, 16);

        accomplish.setColumns(20);
        accomplish.setRows(5);
        accomplish.setToolTipText("Enter a deadline for this goal");
        jScrollPane2.setViewportView(accomplish);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(16, 262, 396, 84);

        jButton1.setText("Save");
        jButton1.setToolTipText("Save goal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(74, 364, 75, 29);

        settings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/settings2.jpg"))); // NOI18N
        settings.setToolTipText("Settings");
        settings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsActionPerformed(evt);
            }
        });
        getContentPane().add(settings);
        settings.setBounds(560, 250, 70, 72);

        new_entry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/addicon.jpg"))); // NOI18N
        new_entry.setToolTipText("Create new goal");
        new_entry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_entryActionPerformed(evt);
            }
        });
        getContentPane().add(new_entry);
        new_entry.setBounds(560, 170, 70, 72);

        feed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/editicon.png"))); // NOI18N
        feed.setToolTipText("Feed/Edit goals");
        feed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedActionPerformed(evt);
            }
        });
        getContentPane().add(feed);
        feed.setBounds(560, 90, 70, 72);

        login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/profileicon.png"))); // NOI18N
        login.setToolTipText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login);
        login.setBounds(560, 10, 70, 72);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stars.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 640, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void settingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsActionPerformed
        SettingsFrameGUI settingsGUI = new SettingsFrameGUI();
        settingsGUI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_settingsActionPerformed

    private void new_entryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_entryActionPerformed
        EditFrameGUI editGUI = new EditFrameGUI(); // parameter can be the user text
        editGUI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_new_entryActionPerformed

    private void feedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedActionPerformed
        FeedFrameGUI feedScreen = new FeedFrameGUI();
        feedScreen.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_feedActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed

        LoginFrameGUI loginScreen = new LoginFrameGUI();
        loginScreen.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditFrameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditFrameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditFrameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditFrameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditFrameGUI().setVisible(true);
            }
        });
    }

    
    
    
    
    
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea accomplish;
    private javax.swing.JButton feed;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton login;
    private javax.swing.JButton new_entry;
    private javax.swing.JTextArea reason_want;
    private javax.swing.JButton settings;
    private javax.swing.JTextField want;
    // End of variables declaration//GEN-END:variables
}
