/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PeterLeung
 */



public class LoginFrameGUI extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrameGUI
     */
    public LoginFrameGUI() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        user_login = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        sign_up = new javax.swing.JButton();
        email_signup = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        user_signup = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(640, 400));
        setMinimumSize(new java.awt.Dimension(655, 435));
        setPreferredSize(new java.awt.Dimension(640, 400));
        setResizable(false);
        setSize(new java.awt.Dimension(655, 435));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 2, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("dreamdazer");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 261, 46);

        jLabel3.setFont(new java.awt.Font("Noteworthy", 2, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 255));
        jLabel3.setText("interactive change");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 50, 180, 22);

        login.setText("login");
        login.setToolTipText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login);
        login.setBounds(140, 230, 76, 29);

        jLabel8.setForeground(new java.awt.Color(0, 255, 255));
        jLabel8.setText("password");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(110, 180, 140, 16);

        user_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_loginActionPerformed(evt);
            }
        });
        getContentPane().add(user_login);
        user_login.setBounds(110, 150, 138, 26);

        jLabel7.setForeground(new java.awt.Color(0, 255, 255));
        jLabel7.setText("user");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(110, 130, 140, 16);

        sign_up.setText("sign up");
        sign_up.setToolTipText("New User");
        sign_up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sign_upActionPerformed(evt);
            }
        });
        getContentPane().add(sign_up);
        sign_up.setBounds(311, 260, 120, 29);
        getContentPane().add(email_signup);
        email_signup.setBounds(300, 230, 138, 26);

        jLabel6.setForeground(new java.awt.Color(0, 255, 255));
        jLabel6.setText("email");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(300, 210, 140, 16);

        jLabel5.setForeground(new java.awt.Color(0, 255, 255));
        jLabel5.setText("password");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(300, 160, 140, 16);
        getContentPane().add(user_signup);
        user_signup.setBounds(300, 130, 138, 26);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/settings2.jpg"))); // NOI18N
        jButton6.setToolTipText("Settings");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(560, 250, 70, 72);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/addicon.jpg"))); // NOI18N
        jButton4.setToolTipText("Create new goal");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(560, 170, 70, 72);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/editicon.png"))); // NOI18N
        jButton3.setToolTipText("Feed/Edit goals");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(560, 90, 70, 72);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/profileicon.png"))); // NOI18N
        jButton2.setToolTipText("Login");
        getContentPane().add(jButton2);
        jButton2.setBounds(560, 10, 70, 72);

        jLabel4.setForeground(new java.awt.Color(0, 255, 255));
        jLabel4.setText("user");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(300, 110, 140, 16);

        jPasswordField1.setText("jPasswordField1");
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(110, 200, 140, 26);

        jPasswordField2.setText("jPasswordField2");
        getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(300, 180, 140, 26);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stars.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 640, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        if(user_login.getText().isEmpty() || jPasswordField1.getText().isEmpty()){
           cloud errorGUI = new cloud();
           errorGUI.setVisible(true);
           this.setVisible(false);
        }
        else{
            FeedFrameGUI feedScreen = new FeedFrameGUI();
            feedScreen.setVisible(true);
            this.setVisible(false);   
        }
    }//GEN-LAST:event_loginActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        FeedFrameGUI feedScreen = new FeedFrameGUI();
        feedScreen.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        SplashScreenFrame splash = new SplashScreenFrame();
        splash.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void sign_upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sign_upActionPerformed
       if(user_signup.getText().isEmpty() || jPasswordField2.getText().isEmpty() || email_signup.getText().isEmpty()){
           cloud errorGUI = new cloud();
           errorGUI.setVisible(true);
           this.setVisible(false);
       }
       else
       {   
        FeedFrameGUI feedScreen = new FeedFrameGUI();
        feedScreen.setVisible(true);
        this.setVisible(false); 
       }
        
        
        
    }//GEN-LAST:event_sign_upActionPerformed

    private void user_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_loginActionPerformed
        
    }//GEN-LAST:event_user_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrameGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField email_signup;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JButton login;
    private javax.swing.JButton sign_up;
    private javax.swing.JTextField user_login;
    private javax.swing.JTextField user_signup;
    // End of variables declaration//GEN-END:variables
}
